version: "3"

# docker run --rm --name courses-database -v courses-data:/var/lib/postgresql/data -p 5432:5432
# -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=courses-db -d postgres:13-alpine
services:
  courses-database:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    volumes:
      - "course-db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=courses-db"
  test-redis:
    image: "redis:7.0.4-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  course-db-data:
  redis-data: